[versions]
accompanistPermissions = "0.37.3"
activityCompose = "1.11.0"
agp = "8.13.0"
appcompat = "1.7.1"
composeBom = "2025.09.01"
converterMoshi = "3.0.0"
coreKtx = "1.17.0"
coreTesting = "1.17.0"
datastoreCore = "1.1.7"
detekt = "1.23.8"
detektCompose = "0.4.27"
espressoCore = "3.7.0"
hiltAndroid = "2.57.2"
hiltNavigationCompose = "1.3.0"
hiltNavigationFragment = "1.3.0"
junit = "5.13.4"
junitJunit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.20"
kotlinxCollectionsImmutable = "0.4.0"
kotlinxCoroutinesTest = "1.10.2"
kotlinxSerializationJson = "1.9.0"
leakcanaryAndroid = "2.14"
lifecycleRuntimeKtx = "2.9.4"
loggingInterceptor = "5.1.0"
mockk = "1.14.6"
moshiKotlin = "1.15.2"
navigationCompose = "2.9.5"
navigationRuntimeAndroid = "2.9.5"
okhttp = "5.1.0"
opentokAndroidSdk = "2.31.0"
retrofit = "3.0.0"
runtimeAndroid = "1.9.2"
testRules = "1.7.0"
testRunner = "1.7.0"
turbine = "1.2.1"
material = "1.13.0"
runtime = "1.9.2"
material3 = "1.4.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
androidx-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout" }
androidx-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-testing = { module = "androidx.core:core-testing", version.ref = "coreTesting" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences", version.ref = "datastoreCore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavigationFragment" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
detekt-compose-rules = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroid" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-junit = { module = "junit:junit", version.ref = "junitJunit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
opentok-android-sdk = { module = "com.opentok.android:opentok-android-sdk", version.ref = "opentokAndroidSdk" }
opentok-android-video-transformers = { module = "com.vonage:client-sdk-video-transformers", version.ref = "opentokAndroidSdk" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version = "2.2.20-2.0.2" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.2" }
play-publisher = { id = "com.github.triplet.play", version = "3.12.1" }
sonarqube = { id = "org.sonarqube", version = "6.3.1.5724" }
